/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Hung
 */
public class DashBoard1 extends javax.swing.JFrame
{

    private boolean check = true;
    private GanTagForm1 ganTagForm;
    private TaoDonForm1 taoDonForm;
    private QuetDonForm1 quetDonForm;
    private BaoCaoForm1 baoCaoForm;
    private LoginForm1 loginForm;

    public DashBoard1(LoginForm1 login)
    {
        ganTagForm = new GanTagForm1();
        taoDonForm = new TaoDonForm1();
        quetDonForm = new QuetDonForm1();
        baoCaoForm = new BaoCaoForm1();
        this.loginForm = login;
        
        setUndecorated(true);
        initComponents();
        setVisible(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DashBoard1.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabelMini = new javax.swing.JLabel();
        jLabelClosed = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        menuIcon = new javax.swing.JPanel();
        linehideMenu = new javax.swing.JPanel();
        hidemenu = new javax.swing.JPanel();
        btnHidemenu = new javax.swing.JLabel();
        settingLogout = new javax.swing.JPanel();
        logout = new javax.swing.JPanel();
        btnLogout = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ganTagPanel = new javax.swing.JPanel();
        ganTagLabel = new javax.swing.JLabel();
        taoDonXuatPanel = new javax.swing.JPanel();
        taoDonXuatLabel = new javax.swing.JLabel();
        quetDonXuatPanel = new javax.swing.JPanel();
        quetDonXuatLabel = new javax.swing.JLabel();
        baoCaoPanel = new javax.swing.JPanel();
        baoCaoLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTaoDon = new javax.swing.JPanel();
        jGanTag = new javax.swing.JPanel();
        jQuetDon = new javax.swing.JPanel();
        jBaoCao = new javax.swing.JPanel();
        jPanelTrinhDo = new javax.swing.JPanel();
        jPanelCaThi = new javax.swing.JPanel();
        jPanelKetQua = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1250, 700));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(212, 236, 189));
        kGradientPanel1.setkStartColor(new java.awt.Color(66, 98, 124));
        kGradientPanel1.setkTransparentControls(false);
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(1250, 700));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1250, 700));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setkEndColor(new java.awt.Color(84, 113, 126));
        kGradientPanel2.setkGradientFocus(1000);
        kGradientPanel2.setkStartColor(new java.awt.Color(84, 113, 126));
        kGradientPanel2.setkTransparentControls(false);
        kGradientPanel2.setMinimumSize(new java.awt.Dimension(1250, 50));
        kGradientPanel2.setPreferredSize(new java.awt.Dimension(1250, 50));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_minimize_window_48.png"))); // NOI18N
        jLabelMini.setToolTipText("Minimize");
        jLabelMini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMini.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabelMiniMouseClicked(evt);
            }
        });
        jLabelMini.addPropertyChangeListener(new java.beans.PropertyChangeListener()
        {
            public void propertyChange(java.beans.PropertyChangeEvent evt)
            {
                jLabelMiniPropertyChange(evt);
            }
        });
        kGradientPanel2.add(jLabelMini, new org.netbeans.lib.awtextra.AbsoluteConstraints(1163, 0, 40, 50));

        jLabelClosed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClosed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1_48.png"))); // NOI18N
        jLabelClosed.setToolTipText("Close");
        jLabelClosed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClosed.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabelClosedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                jLabelClosedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                jLabelClosedMouseExited(evt);
            }
        });
        kGradientPanel2.add(jLabelClosed, new org.netbeans.lib.awtextra.AbsoluteConstraints(1209, 0, 40, 50));

        jLabel6.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kGradientPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 110, 50));

        jLabel8.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(233, 242, 249));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-furniture-store-32.png"))); // NOI18N
        jLabel8.setText("<html> <span>QUẢN LÝ KHO <span> </html> ");
        kGradientPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 50));

        jLabel9.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(167, 193, 169));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_waving_hand_emoji_32.png"))); // NOI18N
        jLabel9.setText("Xin chào");
        kGradientPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 140, 50));

        kGradientPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(81, 113, 131));
        jPanel1.setPreferredSize(new java.awt.Dimension(260, 650));

        menuIcon.setBackground(new java.awt.Color(66, 98, 124));
        menuIcon.setMinimumSize(new java.awt.Dimension(100, 5));
        menuIcon.setPreferredSize(new java.awt.Dimension(50, 650));
        menuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        linehideMenu.setBackground(new java.awt.Color(66, 98, 124));
        linehideMenu.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout linehideMenuLayout = new javax.swing.GroupLayout(linehideMenu);
        linehideMenu.setLayout(linehideMenuLayout);
        linehideMenuLayout.setHorizontalGroup(
            linehideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        linehideMenuLayout.setVerticalGroup(
            linehideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        menuIcon.add(linehideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 5));

        hidemenu.setBackground(new java.awt.Color(66, 98, 124));
        hidemenu.setPreferredSize(new java.awt.Dimension(50, 50));
        hidemenu.setLayout(new java.awt.BorderLayout());

        btnHidemenu.setBackground(new java.awt.Color(66, 98, 124));
        btnHidemenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHidemenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_menu_32.png"))); // NOI18N
        btnHidemenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHidemenu.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnHidemenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnHidemenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                btnHidemenuMouseExited(evt);
            }
        });
        hidemenu.add(btnHidemenu, java.awt.BorderLayout.CENTER);

        menuIcon.add(hidemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 50, -1));

        settingLogout.setBackground(new java.awt.Color(66, 98, 124));
        settingLogout.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout settingLogoutLayout = new javax.swing.GroupLayout(settingLogout);
        settingLogout.setLayout(settingLogoutLayout);
        settingLogoutLayout.setHorizontalGroup(
            settingLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        settingLogoutLayout.setVerticalGroup(
            settingLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        menuIcon.add(settingLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 50, 5));

        logout.setBackground(new java.awt.Color(66, 98, 124));
        logout.setPreferredSize(new java.awt.Dimension(50, 50));
        logout.setLayout(new java.awt.BorderLayout());

        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_exit_32.png"))); // NOI18N
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                btnLogoutMouseExited(evt);
            }
        });
        logout.add(btnLogout, java.awt.BorderLayout.CENTER);

        menuIcon.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 50, 50));

        jPanel3.setBackground(new java.awt.Color(81, 113, 131));

        jPanel5.setBackground(new java.awt.Color(81, 113, 131));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 50));

        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(208, 245, 253));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Menu");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(230, 233, 237)));
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, 38, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ganTagPanel.setBackground(new java.awt.Color(81, 113, 131));
        ganTagPanel.setPreferredSize(new java.awt.Dimension(200, 50));

        ganTagLabel.setFont(new java.awt.Font("DialogInput", 1, 19)); // NOI18N
        ganTagLabel.setForeground(new java.awt.Color(208, 245, 253));
        ganTagLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-tag-window-32.png"))); // NOI18N
        ganTagLabel.setText("GẮN TAG");
        ganTagLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(230, 233, 237)));
        ganTagLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ganTagLabel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                ganTagLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                ganTagLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                ganTagLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ganTagPanelLayout = new javax.swing.GroupLayout(ganTagPanel);
        ganTagPanel.setLayout(ganTagPanelLayout);
        ganTagPanelLayout.setHorizontalGroup(
            ganTagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ganTagLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ganTagPanelLayout.setVerticalGroup(
            ganTagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ganTagLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        taoDonXuatPanel.setBackground(new java.awt.Color(81, 113, 131));
        taoDonXuatPanel.setPreferredSize(new java.awt.Dimension(200, 50));

        taoDonXuatLabel.setFont(new java.awt.Font("DialogInput", 1, 19)); // NOI18N
        taoDonXuatLabel.setForeground(new java.awt.Color(208, 245, 253));
        taoDonXuatLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-create-32.png"))); // NOI18N
        taoDonXuatLabel.setText("TẠO ĐƠN XUẤT");
        taoDonXuatLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(230, 233, 237)));
        taoDonXuatLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        taoDonXuatLabel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                taoDonXuatLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                taoDonXuatLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                taoDonXuatLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout taoDonXuatPanelLayout = new javax.swing.GroupLayout(taoDonXuatPanel);
        taoDonXuatPanel.setLayout(taoDonXuatPanelLayout);
        taoDonXuatPanelLayout.setHorizontalGroup(
            taoDonXuatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(taoDonXuatLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        taoDonXuatPanelLayout.setVerticalGroup(
            taoDonXuatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(taoDonXuatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        quetDonXuatPanel.setBackground(new java.awt.Color(81, 113, 131));
        quetDonXuatPanel.setPreferredSize(new java.awt.Dimension(200, 50));

        quetDonXuatLabel.setFont(new java.awt.Font("DialogInput", 1, 19)); // NOI18N
        quetDonXuatLabel.setForeground(new java.awt.Color(208, 245, 253));
        quetDonXuatLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-scan-32.png"))); // NOI18N
        quetDonXuatLabel.setText("QUÉT ĐƠN XUẤT");
        quetDonXuatLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(230, 233, 237)));
        quetDonXuatLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quetDonXuatLabel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                quetDonXuatLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                quetDonXuatLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                quetDonXuatLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout quetDonXuatPanelLayout = new javax.swing.GroupLayout(quetDonXuatPanel);
        quetDonXuatPanel.setLayout(quetDonXuatPanelLayout);
        quetDonXuatPanelLayout.setHorizontalGroup(
            quetDonXuatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(quetDonXuatLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        quetDonXuatPanelLayout.setVerticalGroup(
            quetDonXuatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(quetDonXuatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        baoCaoPanel.setBackground(new java.awt.Color(81, 113, 131));
        baoCaoPanel.setPreferredSize(new java.awt.Dimension(200, 50));

        baoCaoLabel.setFont(new java.awt.Font("DialogInput", 1, 19)); // NOI18N
        baoCaoLabel.setForeground(new java.awt.Color(208, 245, 253));
        baoCaoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-report-32.png"))); // NOI18N
        baoCaoLabel.setText("BÁO CÁO");
        baoCaoLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(230, 233, 237)));
        baoCaoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        baoCaoLabel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                baoCaoLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                baoCaoLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                baoCaoLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout baoCaoPanelLayout = new javax.swing.GroupLayout(baoCaoPanel);
        baoCaoPanel.setLayout(baoCaoPanelLayout);
        baoCaoPanelLayout.setHorizontalGroup(
            baoCaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(baoCaoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        baoCaoPanelLayout.setVerticalGroup(
            baoCaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(baoCaoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(menuIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(baoCaoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(ganTagPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(quetDonXuatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(taoDonXuatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                .addGap(802, 802, 802))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ganTagPanel, 38, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(taoDonXuatPanel, 38, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(quetDonXuatPanel, 38, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(baoCaoPanel, 38, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(menuIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kGradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jPanel2.setBackground(new java.awt.Color(134, 162, 154));
        jPanel2.setEnabled(false);

        jTaoDon.setLayout(new javax.swing.BoxLayout(jTaoDon, javax.swing.BoxLayout.LINE_AXIS));
        jTaoDon.setVisible (false);

        jGanTag.setLayout(new javax.swing.BoxLayout(jGanTag, javax.swing.BoxLayout.LINE_AXIS));
        jGanTag.setVisible (false);

        jQuetDon.setLayout(new javax.swing.BoxLayout(jQuetDon, javax.swing.BoxLayout.LINE_AXIS));
        jQuetDon.setVisible (false);

        jBaoCao.setLayout(new javax.swing.BoxLayout(jBaoCao, javax.swing.BoxLayout.LINE_AXIS));
        jBaoCao.setVisible (false);

        jPanelTrinhDo.setLayout(new javax.swing.BoxLayout(jPanelTrinhDo, javax.swing.BoxLayout.LINE_AXIS));
        jPanelTrinhDo.setVisible (false);

        jPanelCaThi.setLayout(new javax.swing.BoxLayout(jPanelCaThi, javax.swing.BoxLayout.LINE_AXIS));
        jPanelCaThi.setVisible (false);

        jPanelKetQua.setLayout(new javax.swing.BoxLayout(jPanelKetQua, javax.swing.BoxLayout.LINE_AXIS));
        jPanelKetQua.setVisible (false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gc.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1080, 1080));
        jLabel1.setMinimumSize(new java.awt.Dimension(990, 650));
        jLabel1.setPreferredSize(new java.awt.Dimension(990, 650));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanelCaThi, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jGanTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jQuetDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTaoDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelTrinhDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jPanelKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 19, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jGanTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jQuetDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTaoDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelTrinhDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(650, 655, Short.MAX_VALUE))
            .addComponent(jPanelCaThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jPanelKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTaoDon.add(taoDonForm.getjPanel1());
        //jPanel10.add(pb);
        jGanTag.add(ganTagForm.getjPanel1());
        //jPanel7.add(da);
        jQuetDon.add(quetDonForm.getjPanel1());
        //jPanel8.add (hd);
        jBaoCao.add(baoCaoForm.getjPanel1());
        //jPanel9.add(bcc);
        //jPanelTrinhDo.add(trinhDoForm);
        //jPanel11.add(phucap);
        //jPanelCaThi.add(caThiForm);
        //jPanelKetQua.add(ketQuaForm);

        kGradientPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 990, 650));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 700));
        kGradientPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMiniMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabelMiniMouseClicked
    {//GEN-HEADEREND:event_jLabelMiniMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabelMiniMouseClicked

    /**
     *
     * @param hover
     * @param rand
     */
    public void changecolor(JPanel hover, Color rand)
    {
        hover.setBackground(rand);
    }

    public void changecolor1(JLabel hover1, Color rand)
    {
        hover1.setBackground(rand);
    }

    public void clickMenu(JPanel p1, JPanel p2, int numbool)
    {
        if (numbool == 1)
        {
            changecolor(p1, new Color(81, 113, 131));
            changecolor(p2, new Color(66, 98, 124));
        }
    }

    public void changeIcon(JLabel lb, String src)
    {
        ImageIcon ic = new ImageIcon(getClass().getResource(src));
        lb.setIcon(ic);
    }

    public void hideshowMenu(JPanel p, boolean check, JLabel lb)
    {
        if (check == true)
        {
            p.setPreferredSize(new Dimension(50, 650));
            changeIcon(lb, "/img/icons8_back_32.png");
//            p2.setPreferredSize (new Dimension (1200, 650));
        } else
        {
            p.setPreferredSize(new Dimension(260, 650));
            changeIcon(lb, "/img/icons8_menu_32.png");
//            p2.setPreferredSize (new Dimension (990, 650));
        }
    }

    private void jLabelClosedMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabelClosedMouseClicked
    {//GEN-HEADEREND:event_jLabelClosedMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelClosedMouseClicked

    private void jLabelMiniPropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_jLabelMiniPropertyChange
    {//GEN-HEADEREND:event_jLabelMiniPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMiniPropertyChange

    private void jLabelClosedMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabelClosedMouseEntered
    {//GEN-HEADEREND:event_jLabelClosedMouseEntered
//        changecolor (jLabel3, new Color(232, 68, 82));
    }//GEN-LAST:event_jLabelClosedMouseEntered

    private void jLabelClosedMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabelClosedMouseExited
    {//GEN-HEADEREND:event_jLabelClosedMouseExited
//         changecolor (jLabel3, new Color(232, 68, 82));
    }//GEN-LAST:event_jLabelClosedMouseExited

    private void btnHidemenuMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnHidemenuMouseEntered
    {//GEN-HEADEREND:event_btnHidemenuMouseEntered
        changecolor(linehideMenu, new Color(210, 226, 199));
    }//GEN-LAST:event_btnHidemenuMouseEntered

    private void btnHidemenuMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnHidemenuMouseClicked
    {//GEN-HEADEREND:event_btnHidemenuMouseClicked
        clickMenu(hidemenu, logout, 1);
        if (check == true)
        {
            hideshowMenu(jPanel1, check, btnHidemenu);
//              changeIcon (btnHidemenu, check);
            SwingUtilities.updateComponentTreeUI(this);
            check = false;
        } else
        {
            hideshowMenu(jPanel1, check, btnHidemenu);
//            changeIcon (btnHidemenu, check);
            SwingUtilities.updateComponentTreeUI(this);
            check = true;
        }

    }//GEN-LAST:event_btnHidemenuMouseClicked

    private void btnHidemenuMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnHidemenuMouseExited
    {//GEN-HEADEREND:event_btnHidemenuMouseExited
        changecolor(linehideMenu, new Color(66, 98, 124));
    }//GEN-LAST:event_btnHidemenuMouseExited

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnLogoutMouseClicked
    {//GEN-HEADEREND:event_btnLogoutMouseClicked
        clickMenu(logout, hidemenu, 1);
        int confirm = JOptionPane.showConfirmDialog(DashBoard1.this, "Bạn muốn đăng xuất?",
                "Xác Nhận", JOptionPane.OK_CANCEL_OPTION);
        if (confirm == JOptionPane.OK_OPTION)
        {
            LoginForm1.flag = 0;
            this.setVisible(false);
            loginForm.setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnLogoutMouseEntered
    {//GEN-HEADEREND:event_btnLogoutMouseEntered
        changecolor(settingLogout, new Color(197, 64, 51));
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnLogoutMouseExited
    {//GEN-HEADEREND:event_btnLogoutMouseExited
        changecolor(settingLogout, new Color(66, 98, 124));
    }//GEN-LAST:event_btnLogoutMouseExited

    private void quetDonXuatLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_quetDonXuatLabelMouseClicked
    {//GEN-HEADEREND:event_quetDonXuatLabelMouseClicked

        jTaoDon.setVisible(false);
        jGanTag.setVisible(false);
        jQuetDon.setVisible(true);
        jBaoCao.setVisible(false);
        quetDonForm.createTableDon();
    }//GEN-LAST:event_quetDonXuatLabelMouseClicked

    private void quetDonXuatLabelMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_quetDonXuatLabelMouseEntered
    {//GEN-HEADEREND:event_quetDonXuatLabelMouseEntered
        changecolor(quetDonXuatPanel, new Color(107, 138, 164));
    }//GEN-LAST:event_quetDonXuatLabelMouseEntered

    private void quetDonXuatLabelMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_quetDonXuatLabelMouseExited
    {//GEN-HEADEREND:event_quetDonXuatLabelMouseExited
        changecolor(quetDonXuatPanel, new Color(81, 113, 131));
    }//GEN-LAST:event_quetDonXuatLabelMouseExited

    private void baoCaoLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_baoCaoLabelMouseClicked
    {//GEN-HEADEREND:event_baoCaoLabelMouseClicked

        jTaoDon.setVisible(false);
        jGanTag.setVisible(false);
        jQuetDon.setVisible(false);
        jBaoCao.setVisible(true);
        baoCaoForm.createTableDon();
        LoginForm1.flag = 0;
        LoginForm1.tagMap.clear();
    }//GEN-LAST:event_baoCaoLabelMouseClicked

    public GanTagForm1 getGanTagForm()
    {
        return ganTagForm;
    }

    public void setGanTagForm(GanTagForm1 ganTagForm)
    {
        this.ganTagForm = ganTagForm;
    }

    public QuetDonForm1 getQuetDonForm()
    {
        return quetDonForm;
    }

    public void setQuetDonForm(QuetDonForm1 quetDonForm)
    {
        this.quetDonForm = quetDonForm;
    }

    private void baoCaoLabelMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_baoCaoLabelMouseEntered
    {//GEN-HEADEREND:event_baoCaoLabelMouseEntered
        changecolor(baoCaoPanel, new Color(107, 138, 164));
    }//GEN-LAST:event_baoCaoLabelMouseEntered

    private void baoCaoLabelMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_baoCaoLabelMouseExited
    {//GEN-HEADEREND:event_baoCaoLabelMouseExited
        changecolor(baoCaoPanel, new Color(81, 113, 131));
    }//GEN-LAST:event_baoCaoLabelMouseExited

    private void ganTagLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ganTagLabelMouseExited
        changecolor(ganTagPanel, new Color(81, 113, 131));
    }//GEN-LAST:event_ganTagLabelMouseExited

    private void ganTagLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ganTagLabelMouseEntered
        changecolor(ganTagPanel, new Color(107, 138, 164));
    }//GEN-LAST:event_ganTagLabelMouseEntered

    private void ganTagLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ganTagLabelMouseClicked

        jGanTag.setVisible(true);
        jQuetDon.setVisible(false);
        jTaoDon.setVisible(false);
        jBaoCao.setVisible(false);
        ganTagForm.createTableSanPham();

        LoginForm1.flag = 1;
        LoginForm1.tagMap.clear();
    }//GEN-LAST:event_ganTagLabelMouseClicked

    private void taoDonXuatLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_taoDonXuatLabelMouseClicked
    {//GEN-HEADEREND:event_taoDonXuatLabelMouseClicked

        jQuetDon.setVisible(false);
        jTaoDon.setVisible(true);
        jGanTag.setVisible(false);
        jBaoCao.setVisible(false);
        taoDonForm.createTableSanPham();
        LoginForm1.flag = 0;
        LoginForm1.tagMap.clear();
    }//GEN-LAST:event_taoDonXuatLabelMouseClicked

    private void taoDonXuatLabelMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_taoDonXuatLabelMouseEntered
    {//GEN-HEADEREND:event_taoDonXuatLabelMouseEntered
        // TODO add your handling code here:
        changecolor(taoDonXuatPanel, new Color(107, 138, 164));
    }//GEN-LAST:event_taoDonXuatLabelMouseEntered

    private void taoDonXuatLabelMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_taoDonXuatLabelMouseExited
    {//GEN-HEADEREND:event_taoDonXuatLabelMouseExited
        // TODO add your handling code here:
        changecolor(taoDonXuatPanel, new Color(81, 113, 131));
    }//GEN-LAST:event_taoDonXuatLabelMouseExited

//   public JLabel getjLabel5()
//    {
//        return jLabel5;
//    }
//
//    public void setjLabel5(JLabel jLabel5)
//    {
//        this.jLabel5 = jLabel5;
//    }
    public JLabel getBtnHidemenu()
    {
        return btnHidemenu;
    }

    public void setBtnHidemenu(JLabel btnHidemenu)
    {
        this.btnHidemenu = btnHidemenu;
    }

    public JLabel getBtnLogout()
    {
        return btnLogout;
    }

    public void setBtnLogout(JLabel btnLogout)
    {
        this.btnLogout = btnLogout;
    }

    public JLabel getHopdongLabel()
    {
        return baoCaoLabel;
    }

    public void setHopdongLabel(JLabel hopdongLabel)
    {
        this.baoCaoLabel = hopdongLabel;
    }

    public JLabel getNhanvienLabel()
    {
        return ganTagLabel;
    }

    public void setNhanvienLabel(JLabel nhanvienLabel)
    {
        this.ganTagLabel = nhanvienLabel;
    }

    public JLabel getPbLabel()
    {
        return quetDonXuatLabel;
    }

    public void setPbLabel(JLabel pbLabel)
    {
        this.quetDonXuatLabel = pbLabel;
    }

    public JLabel getjLabelClosed()
    {
        return jLabelClosed;
    }

    public void setjLabelClosed(JLabel jLabelClosed)
    {
        this.jLabelClosed = jLabelClosed;
    }

    public JLabel getjLabelMini()
    {
        return jLabelMini;
    }

    public void setjLabelMini(JLabel jLabelMini)
    {
        this.jLabelMini = jLabelMini;
    }

    public JLabel getjLabel6()
    {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6)
    {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel9()
    {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9)
    {
        this.jLabel9 = jLabel9;
    }

    public JPanel getGanTagPanel()
    {
        return ganTagPanel;
    }

    public void setGanTagPanel(JPanel ganTagPanel)
    {
        this.ganTagPanel = ganTagPanel;
    }

    public JPanel getjBaoCao()
    {
        return jBaoCao;
    }

    public void setjBaoCao(JPanel jBaoCao)
    {
        this.jBaoCao = jBaoCao;
    }

    public JPanel getjCreateOrder()
    {
        return jTaoDon;
    }

    public void setjCreateOrder(JPanel jCreateOrder)
    {
        this.jTaoDon = jCreateOrder;
    }

    public JPanel getjInput()
    {
        return jGanTag;
    }

    public void setjInput(JPanel jInput)
    {
        this.jGanTag = jInput;
    }

    public JPanel getjOrder()
    {
        return jQuetDon;
    }

    public void setjOrder(JPanel jOrder)
    {
        this.jQuetDon = jOrder;
    }

    public JLabel getjLabel1()
    {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1)
    {
        this.jLabel1 = jLabel1;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel baoCaoLabel;
    private javax.swing.JPanel baoCaoPanel;
    private javax.swing.JLabel btnHidemenu;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel ganTagLabel;
    private javax.swing.JPanel ganTagPanel;
    private javax.swing.JPanel hidemenu;
    private javax.swing.JPanel jBaoCao;
    private javax.swing.JPanel jGanTag;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClosed;
    private javax.swing.JLabel jLabelMini;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelCaThi;
    private javax.swing.JPanel jPanelKetQua;
    private javax.swing.JPanel jPanelTrinhDo;
    private javax.swing.JPanel jQuetDon;
    private javax.swing.JPanel jTaoDon;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JPanel linehideMenu;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel menuIcon;
    private javax.swing.JLabel quetDonXuatLabel;
    private javax.swing.JPanel quetDonXuatPanel;
    private javax.swing.JPanel settingLogout;
    private javax.swing.JLabel taoDonXuatLabel;
    private javax.swing.JPanel taoDonXuatPanel;
    // End of variables declaration//GEN-END:variables

}
