/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.NhapExcel;
import BUS.SanPhamBUS;
import BUS.RFIDTagBUS;
import DTO.SanPhamDTO;
import DTO.RFIDTagDTO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Set;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hung
 */
public class GanTagForm1 extends javax.swing.JFrame
{

    int rowTag = -2, rowProduct = -2;
    boolean selectedTag = false, selectedProduct = false;
    String idTag = "", idProduct = "";

    DefaultTableModel tbModelTag, tbModelSanPham;
    public static ArrayList<RFIDTagDTO> tagList = new ArrayList<>();
    Set<String> tags;
    SanPhamBUS sanPhamBUS = new SanPhamBUS();
    RFIDTagBUS tagBUS = new RFIDTagBUS();

    public GanTagForm1()
    {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setVisible(false);
        createTableTag();
        createTableSanPham();
        jBtnAdd.setEnabled(false);
    }

    public void creatTableModelTag(DefaultTableModel model)
    {
        for (RFIDTagDTO tag : tagList)
        {
            System.out.println("tag: " + tag);
            Vector row = new Vector();
            row.add(tag.getTagId());
            model.addRow(row);
        }
    }

    public void createTableTag()
    {
        tbModelTag.setRowCount(0);
        creatTableModelTag(tbModelTag);
        jTableTag.setRowSorter(null);
        jTableTag.setAutoCreateRowSorter(true);
        jTableTag.setModel(tbModelTag);
        jTableTag.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void createTagAuto()
    {
        tbModelTag.setRowCount(0);
        creatTableModelTag(tbModelTag);
    }

    public void createTableModelSanPham(DefaultTableModel model)
    {
        sanPhamBUS = new SanPhamBUS();
        for (SanPhamDTO sanPham : sanPhamBUS.getList())
        {
            Vector row = new Vector();
            row.add(sanPham.getProductId());
            row.add(sanPham.getProductName());
            row.add(sanPham.getProductQuantity());
            row.add(sanPham.getProductDetail());
            model.addRow(row);
        }
    }

    public void createTableSanPham()
    {
        clear();
        tbModelSanPham.setRowCount(0);
        createTableModelSanPham(tbModelSanPham);
        jTableSanPham.setModel(tbModelSanPham);
        jTableSanPham.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    void clear()
    {
        rowProduct = -2;
        rowTag = -2;
        tbModelTag.setRowCount(0);
        jTableTag.clearSelection();
        jTableSanPham.clearSelection();
        selectedTag = false;
        selectedProduct = false;
        jBtnAdd.setEnabled(false);
        if (!tagList.isEmpty())
        {
            tagList.clear();
        }
    }

    public void updateTableModelTag()
    {
        for (int i = 0; i < tbModelTag.getRowCount(); i++)
        {
            if (idTag.equals(tbModelTag.getValueAt(i, 0)))
            {
                System.out.println("remove");
                tbModelTag.removeRow(i);
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTag = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSanPham = new javax.swing.JTable();
        jBtnAdd = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jBtnNhap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(990, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NHẬP CÁC TAG");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 243, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("DANH SÁCH TAG");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 163, 40));

        Vector tableCol=new Vector();
        tableCol.add("Tag ID");

        tbModelTag = new DefaultTableModel (tableCol,0)
        {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return false;
            }
        };
        jTableTag.setModel (tbModelTag);
        jTableTag.setShowGrid(true);
        jTableTag.setFocusable(false);
        //        jTableTag.setIntercellSpacing(new Dimension(0,0));
        jTableTag.setRowHeight(25);
        //        jTableTag.setRowMargin(10);
        jTableTag.getTableHeader().setOpaque(false);
        jTableTag.setFillsViewportHeight(true);
        jTableTag.getTableHeader().setBackground(new Color(220,220,220));
        jTableTag.getTableHeader().setForeground(new Color(30,30,30));
        jTableTag.getTableHeader().setFont (new Font("Dialog", Font.BOLD, 13));
        jTableTag.setSelectionBackground(new Color(0,120,215));
        jTableTag.setSelectionForeground(new Color(255,255,255));
        jTableTag.setForeground(new Color(30,30,30));
        jTableTag.setAutoCreateRowSorter(true);
        jTableTag.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableTag.setGridColor(new java.awt.Color(83, 86, 88));
        jTableTag.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTableTagMouseClicked(evt);
            }
        });
        jTableTag.getColumn (tableCol.elementAt (0)).setPreferredWidth (230);
        jTableTag.setAutoResizeMode (javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTableTag);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 250, 430));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("DANH SÁCH SẢN PHẨM");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 163, 40));

        Vector tableColProduct = new Vector();
        tableColProduct.add("ID Sản Phẩm");
        tableColProduct.add("Tên Sản Phẩm");
        tableColProduct.add("Số Lượng");
        tableColProduct.add("Chi Tiết Sản Phẩm");

        tbModelSanPham = new DefaultTableModel (tableColProduct,0)
        {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return false;
            }
        };
        jTableSanPham.setModel (tbModelSanPham);
        jTableSanPham.setShowGrid(true);
        jTableSanPham.setFocusable(false);
        //        jTableSanPham.setIntercellSpacing(new Dimension(0,0));
        jTableSanPham.setRowHeight(25);
        //        jTableSanPham.setRowMargin(20);
        jTableSanPham.getTableHeader().setOpaque(false);
        jTableSanPham.setFillsViewportHeight(true);
        jTableSanPham.getTableHeader().setBackground(new Color(220,220,220));
        jTableSanPham.getTableHeader().setForeground(new Color(30, 30, 30));
        jTableSanPham.getTableHeader().setFont (new Font("Dialog", Font.BOLD, 13));
        jTableSanPham.setSelectionBackground(new Color(0,120,215));
        jTableSanPham.setSelectionForeground(new Color(255,255,255));
        jTableSanPham.setForeground(new Color(30,30,30));
        jTableSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableSanPham.setGridColor(new java.awt.Color(83, 86, 88));
        jTableSanPham.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTableSanPhamMouseClicked(evt);
            }
        });
        jTableSanPham.getColumn (tableColProduct.elementAt (0)).setPreferredWidth (100);
        jTableSanPham.getColumn (tableColProduct.elementAt (1)).setPreferredWidth (200);
        jTableSanPham.getColumn (tableColProduct.elementAt (2)).setPreferredWidth (100);
        jTableSanPham.getColumn (tableColProduct.elementAt (3)).setPreferredWidth (300);
        jTableSanPham.setAutoResizeMode (javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jTableSanPham);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 620, 430));

        jBtnAdd.setBackground(new java.awt.Color(255, 255, 255));
        jBtnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_checked_32.png"))); // NOI18N
        jBtnAdd.setBorder(null);
        jBtnAdd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnAddActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 110, 40, 42));

        jButtonRefresh.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_refresh_32.png"))); // NOI18N
        jButtonRefresh.setBorder(null);
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 40, 40));

        jBtnNhap.setBackground(new java.awt.Color(255, 255, 255));
        jBtnNhap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_microsoft_excel_32.png"))); // NOI18N
        jBtnNhap.setBorder(null);
        jBtnNhap.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnNhapActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 115, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableTagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTagMouseClicked
        // TODO add your handling code here:
        int row = jTableTag.getSelectedRow();
        System.out.println("row: " + row);

        if (row != -1)
        {
            selectedTag = true;
            rowTag = row;
            idTag = (String) jTableTag.getValueAt(rowTag, 0);
            System.out.println(idTag);
        }

        if (selectedTag && selectedProduct && idTag != "" && idProduct != "")
        {
            jBtnAdd.setEnabled(true);
        }
    }//GEN-LAST:event_jTableTagMouseClicked

    private void jTableSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSanPhamMouseClicked
        // TODO add your handling code here:
        int row = jTableSanPham.getSelectedRow();
        System.out.println("row: " + row);
        System.out.println("RowProduc: " + rowProduct);

        if (row != -1)
        {
            System.out.println("Dô dây");
            selectedProduct = true;
            rowProduct = row;
            idProduct = (String) jTableSanPham.getValueAt(rowProduct, 0);
            System.out.println(idProduct);
        }

        if (selectedTag && selectedProduct && idTag != "" && idProduct != "")
        {
            jBtnAdd.setEnabled(true);
        }
    }//GEN-LAST:event_jTableSanPhamMouseClicked

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
        // TODO add your handling code here:
        RFIDTagDTO tagDTO = new RFIDTagDTO(idTag, idProduct, "", null, "", null, "");
        RFIDTagDTO tagTempDTO = new RFIDTagDTO();

        for (RFIDTagDTO tag : tagList)
        {
            if (tag.getTagId().equals(idTag))
            {
                tagDTO.setTagGateIn(tag.getTagGateIn());
                tagDTO.setTagDateIn(tag.getTagDateIn());
                tagTempDTO = tag;
                break;
            }
        }

        if (tagBUS.insertTag(tagDTO))
        {
            SanPhamDTO sanPhamDTO = new SanPhamDTO();
            sanPhamDTO.setProductId((String) tbModelSanPham.getValueAt(rowProduct, 0));
            sanPhamDTO.setProductQuantity((Integer) tbModelSanPham.getValueAt(rowProduct, 2) + 1);

            if (sanPhamBUS.updateProduct(sanPhamDTO))
            {
                jTableSanPham.setValueAt((Integer) tbModelSanPham.getValueAt(rowProduct, 2) + 1, rowProduct, 2);
                updateTableModelTag();
                JOptionPane.showMessageDialog(this, "Gán tag Ok!!!!");
                jTableTag.clearSelection();
                jTableSanPham.clearSelection();
                rowProduct = -2;
                rowTag = -2;
                selectedTag = false;
                selectedProduct = false;
                jBtnAdd.setEnabled(false);
                if (tagList.remove(tagTempDTO))
                {
                    System.out.println("OK!!! Xoa");
                } else
                {
                    System.out.println("Not xoa!!");
                }
            }
        } else
        {
            JOptionPane.showMessageDialog(this, "Gán tag thất bại!!!!");
        }
    }//GEN-LAST:event_jBtnAddActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonRefreshActionPerformed
    {//GEN-HEADEREND:event_jButtonRefreshActionPerformed
        // TODO add your handling code here:
        tbModelTag.setRowCount(0);
        creatTableModelTag(tbModelTag);
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jBtnNhapActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnNhapActionPerformed
    {//GEN-HEADEREND:event_jBtnNhapActionPerformed
        // TODO add your handling code here:
        System.out.println("GẮN TAG AUTO!!!!");
        ArrayList<RFIDTagDTO> listAuto = new ArrayList<>();
        try
        {
            listAuto = NhapExcel.getList();
        } catch (IOException ex)
        {
            System.out.println("Lôi Nhap Auto " + ex.getMessage());
        }

        for (RFIDTagDTO tagDTO : listAuto)
        {
            System.out.println(tagDTO);
            if (tagBUS.insertTag(tagDTO))
            {
                System.out.println("====>Thêm auto Tag đa ok!!!");
                SanPhamDTO sanPhamDTO = new SanPhamDTO();
                sanPhamDTO.setProductId((String) tagDTO.getProductId());
                int quantity = tagBUS.countSanPhamId(tagDTO.getProductId().toString());
                System.out.println("So luong la: " + quantity);
                sanPhamDTO.setProductQuantity((Integer) quantity);
                System.out.println("Quantity cua SAnphamDTO moi ne!!: " + sanPhamDTO.getProductQuantity());
                if (sanPhamBUS.updateProduct(sanPhamDTO))
                {
                    System.out.println("Thêm quantity OK!!!1");
                }
            } else
            {
                JOptionPane.showMessageDialog(this, "Gán Tag Tự Động Thất Bại!!!!");
            }
        }
        createTableSanPham();

    }//GEN-LAST:event_jBtnNhapActionPerformed

    public JPanel getjPanel1()
    {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1)
    {
        this.jPanel1 = jPanel1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnNhap;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableSanPham;
    private javax.swing.JTable jTableTag;
    // End of variables declaration//GEN-END:variables
}
